Add the QueueReader plugin.
jaor/xmobar pull request #568
Opened 2021-09-14 19:36 UTC by guygastineau

* A queue reader for xmobar using `TQueue a` from `stm`.
    This is a flexible and performat solution for sharing
    data between arbitrary haskell and xmobar.
  * I am not sure if I did the haddocks correctly.

---

Should there be an safe and unsafe version?  If `stripActions` were exposed, then users could make their own safe version trivially.  Let me know.

I ran `hlint`.  No errors in the whole codebase.  Awesome maintenance job you all!

---

I didn't make any tests.  Tests seem hard and unnecessary for this.  The plugin is very simple, so it practically feels tautological, but it feels arrogant to say this.

Let me know if I should make any improvements.

2021-09-14 19:44 UTC, guygastineau commented
Inspired by #567

2021-09-14 20:20 UTC, jaor approved these changes

2021-09-14 20:27 UTC, jaor commented
Thanks Guy, this looks good... i think exposing in the library
stripActions is a good idea; having also a safe version would be useful
for people not using xmobar as a library, but, iiuc, they won't be using
this module at all!  would it be possible to have some docs for it in
doc/plugins.org (somewhere near
https://github.com/jaor/xmobar/blob/master/doc/plugins.org#L1418)?
Thanks again!

2021-09-14 20:32 UTC, guygastineau commented
Sure. I will add some docs.  Also, I realized my unicode troubles are not as simple as I thought.  Somehow when I use this unicode that should render in the font I am using doesn't get rendered correctly.  Do you know why?  I would like to fix it before this gets merged.

2021-09-14 21:14 UTC, guygastineau commented
This is an example of the unicode breakage in the `QueueReader`.

![broken-unicode](https://user-images.githubusercontent.com/38230885/133334169-2c7e3b53-6e07-4246-a00d-ae10f58ff0d9.png)

In that image I set middot `·` as the `PP` separator from xmonad:

``` haskell
  , ...
  , ppSep = "\x00b7"
  , ...
```

Xmobar prints that character as well as other font icons, as you can see from my weather section to the right, correctly everywhere except withint the `QueueReader` area of the display.

I am writing to it from xmobar like this by overriding my `ppOutput`:

``` haskell

dynamicLogWithPP pp { ppOutput = STM.atomically . STM.writeTQueue q }
```

Unicode works in that section when I use `StdinReader`, and as you can see my ``xpm icons are still working.  I am just stuck figuring this out...

2021-09-14 21:17 UTC, liskin commented
If you're using xmonad before https://github.com/xmonad/xmonad-contrib/pull/471 got merged (and there was unfortunately no release after that), then that's a known bug in xmonad.

2021-09-14 21:19 UTC, liskin commented
For a quick fix, apply https://hackage.haskell.org/package/utf8-string-1.0.2/docs/Codec-Binary-UTF8-String.html#v:decodeString before writing to the queue. And then don't forget to drop this when you upgrade xmonad.

2021-09-14 21:33 UTC, guygastineau commented
@liskin you are so very helpful! <3  I just decided to vendor `xmonad` and `xmonad-contrib` in my project, since I might want to hack on them too anyway (I am really enjoying how flexible cabal the tool feels after so long with stack.  I am building from master right now, so I guess that will fix it for me.

I guess that means I just need to add some documentation to this PR then.  thanks again.

2021-09-15 00:48 UTC, guygastineau commented
Okay, I think I made some alright docs for `QueueReader a`.  It needs proof-reading for language and review for typos in the extended example again before merging.

2021-09-15 00:49 UTC, guygastineau commented
The example is a little long, but I thought it was better than just regurgitating the contrived example included with the source code.

2021-09-15 01:03 UTC, jaor requested changes
thanks for the docs, they look good (and i like the extended
example) i just pointed out a typo below.

[edit: misunderstanding on my part about docs removed]

2021-09-15 01:03 UTC, jaor commented on doc/plugins.org
> + - This plugin is only usefule if you are running xmobar from another
typo: useful

2021-09-15 01:06 UTC, jaor commented
oh, forget about my rant on the placement of the doc section.  it's already where i was asking!!!

2021-09-15 01:22 UTC, guygastineau commented on doc/plugins.org
> + - This plugin is only usefule if you are running xmobar from another
I force pushed an ammendment (I figured I would need to rebase if I pushed a commit just to fix the typo anyway).  This way, probably no rebase or squash is necessary unless you really love terseness.  Do you do fast forwards?  We don't want to get on Linus' bad side lol

So, you are still okay with the STM section?  I know you retracted when you realized it was placed where you asked.  The way I see I am using the plugin to log from XMonad, but this plugin, can be used to do more general things.  I am not sure if anyone would need it, but TQueues with a custom printer could be used to pass practically anything into xmobar.  Anyway, I agree at least that it makes sense having it near the HandleReader as they are very similar.

2021-09-15 01:27 UTC, jaor commented on doc/plugins.org
> + - This plugin is only usefule if you are running xmobar from another
yes, i think we're fine right now... and i usually prefer ff, yes, although it's a big deal... i'll let the CI run and merge!

2021-09-15 01:45 UTC, merged