Ipc improvements when used from other Haskell code
jaor/xmobar pull request #574
Opened 2021-09-26 03:56 UTC by jsoo1

I think this needs some documentation and thought but I can confirm that I can send signals to xmobar without dbus by keeping around the TMVar.

2021-10-03 03:49 UTC, guygastineau commented on src/Xmobar/Config/Types.hs
> +  readsPrec _ s = [ (SignalChan Nothing, s) ]
Why should there be a real read instance?  Maybe I misunderstand, but it seems like using the channel require access to the `TMVar` which should come from the client?  That is, am I correct in assuming that an empty signal channel read from a config is unusable for calling code?

2021-10-03 03:51 UTC, guygastineau commented
Is this about Intra-Process Communication as opposed to Inter-Process Communication?

2021-10-03 08:33 UTC, jsoo1 commented on src/Xmobar/Config/Types.hs
> +  readsPrec _ s = [ (SignalChan Nothing, s) ]
I left the empty Read instance so that users who compile xmobar and spawn it as a separate os process or have a 'standard' configuration file don't end up making a TMVar that they never use.  Really this is for people using xmonad or some other haskell wm who want to use xmobar more like a library.

2021-10-03 08:34 UTC, jsoo1 commented
> Is this about Intra-Process Communication as opposed to Inter-Process Communication?

ha! i suppose so!

2021-10-03 08:38 UTC, jsoo1 commented on src/Xmobar/Config/Types.hs
> +  readsPrec _ s = [ (SignalChan Nothing, s) ]
An alternative I played with was to accept `Maybe TMVar` in `xmobar` as a second parameter and that removes the need to have it in the config but it doesn't feel quite as nice for the calling code

2021-10-03 08:44 UTC, jsoo1 commented
i think there is also a possibility of providing some signalling mechanism back to xmonad or some other wm that could potentially be a nicer alternative to `action`s, too. i imagine that should probably be done in conjunction with this for a release.

2021-10-03 08:46 UTC, jsoo1 commented on src/Xmobar/Config/Types.hs
> +  readsPrec _ s = [ (SignalChan Nothing, s) ]
in other words, if you are using xmobar from an xmonad.hs then you can use the signal channel, otherwise, xmobar should create one and do the normal execution with os signal handling setup and such.

2021-10-03 20:12 UTC, guygastineau commented on src/Xmobar/Config/Types.hs
> +  readsPrec _ s = [ (SignalChan Nothing, s) ]
The convention that I followed when I made the QueueReader plugin was a failing Read instance which I copied from `HandleReader`:

``` haskell
-- | WARNING: This read instance will throw an exception if used! It is
-- only implemented, because it is required by 'Xmobar.Run` in 'Xmobar.commands'.
instance Read (QueueReader a) where
  -- | Throws an 'error'!
  readsPrec = error "QueueReader: instance is a stub"
```

While this still feels hacky, I think it is better to fail loud and hard if someone tries to add these unreadable plugins to a text config.

2021-10-03 20:14 UTC, guygastineau commented on src/Xmobar/Config/Types.hs
> +  readsPrec _ s = [ (SignalChan Nothing, s) ]
Using the failing `Read` also makes it clear that the `STM` object doesn't belong in the config datatype.

2021-10-03 20:23 UTC, guygastineau commented on src/Xmobar/Config/Types.hs
> +newtype SignalChan = SignalChan { unSignalChan :: Maybe (STM.TMVar SignalType) }
If the `signal` field isn't in the `Config` type, then this doesn't need to be wrapped in Maybe.  When I look at this without `Maybe _`, I realize this is just a specialization of the type constructor `STM.TMVar a`.  Wouldn't it be better to add a `VarReader` (or some more sensible name) plugin to out `STM` plugin collection that can then be specialized by client code?  That way I can make a `VarReader SignalType` from an `STM.TMVar SignalType` that I make in main.  This can then be put in the `commands` field, and the surface of `Config` never has to change.  This is the point of Plugins as I understand them, and I think this kind of generalization is important to maintain flexibility for users.

2021-10-03 20:28 UTC, guygastineau commented on src/Xmobar/Config/Types.hs
> +newtype SignalChan = SignalChan { unSignalChan :: Maybe (STM.TMVar SignalType) }
Oh, I see, this doesn't display anything (duh), so a `VarReader a` wouldn't be very useful.  You can probably just disregard my review then.

2021-10-03 20:28 UTC, guygastineau commented on src/Xmobar/Config/Types.hs
> +newtype SignalChan = SignalChan { unSignalChan :: Maybe (STM.TMVar SignalType) }
Can `SignalType`s already be sent via the dbus plugin?

2021-10-05 02:12 UTC, jaor commented
@jsoo1 you pushed a patch changing alsactl, which seems unrelated to this PR: was that an accident?

2021-10-05 02:22 UTC, jsoo1 commented
Yes. Pardon me

> On Monday, Oct 04, 2021 at 7:12 PM, jao ***@***.*** ***@***.***)> wrote:
>
>
>
>
> @jsoo1 (https://urldefense.com/v3/__https://github.com/jsoo1__;!!IKRxdwAv5BmarQ!NyAoUdZB6O0Ajoo8hyqcwKFnYG-pKKYdSc_r3IBg2l7sXgi-hpOrKNEcf-XlWw$) you pushed a patch changing alsactl, which seems unrelated to this PR: was that an accident?
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://urldefense.com/v3/__https://github.com/jaor/xmobar/pull/574*issuecomment-934000675__;Iw!!IKRxdwAv5BmarQ!NyAoUdZB6O0Ajoo8hyqcwKFnYG-pKKYdSc_r3IBg2l7sXgi-hpOrKNEqg6x5dg$), or unsubscribe (https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ACMTD2PNXUCQDZAPC57XZCLUFJNJZANCNFSM5EYKDLEQ__;!!IKRxdwAv5BmarQ!NyAoUdZB6O0Ajoo8hyqcwKFnYG-pKKYdSc_r3IBg2l7sXgi-hpOrKNEYmBCyIQ$).
>
>
>

2021-10-16 22:25 UTC, jaor commented
@jsoo1 apologies, i lost track of this PR... are we in a good state for reviewing and, eventually, merging? (well, i'm afraid i pushed other patches and you'd need at least a rebase, but hopefully those other changes are not affecting yours directly) @guygastineau any thoughts from your side?  thanks both!

2021-10-16 22:32 UTC, jsoo1 commented
No problem! I think I still need to address some comments and it could use a bit of design review still.

> On Saturday, Oct 16, 2021 at 3:25 PM, jao ***@***.*** ***@***.***)> wrote:
>
>
>
>
> @jsoo1 (https://urldefense.com/v3/__https://github.com/jsoo1__;!!IKRxdwAv5BmarQ!L6fAwsirFxejV2m6bxfUfRaAXp3yhEPOjuSx6QuFFSEzXxZ_v6rhQzKPfz_OpQ$) apologies, i lost track of this PR... are we in a good state for reviewing and, eventually, merging? (well, i'm afraid i pushed other patches and you'd need at least a rebase, but hopefully those other changes are not affecting yours directly) @guygastineau (https://urldefense.com/v3/__https://github.com/guygastineau__;!!IKRxdwAv5BmarQ!L6fAwsirFxejV2m6bxfUfRaAXp3yhEPOjuSx6QuFFSEzXxZ_v6rhQzKE8e_leQ$) any thoughts from your side? thanks both!
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://urldefense.com/v3/__https://github.com/jaor/xmobar/pull/574*issuecomment-945015411__;Iw!!IKRxdwAv5BmarQ!L6fAwsirFxejV2m6bxfUfRaAXp3yhEPOjuSx6QuFFSEzXxZ_v6rhQzKQhyH_hA$), or unsubscribe (https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ACMTD2JFKVWRNDV47AUCBE3UHH3XDANCNFSM5EYKDLEQ__;!!IKRxdwAv5BmarQ!L6fAwsirFxejV2m6bxfUfRaAXp3yhEPOjuSx6QuFFSEzXxZ_v6rhQzLmF1aRXA$).
>
>
>

2021-10-18 13:09 UTC, guygastineau requested changes
I still have the same gripe, but I think I managed not be completely wrong about it this time ;)  I think a dummy read instance for a type that should never be read should fail hard and loud.  I know it needs the instance due to the read constraint on `Config` (which maybe we don't even need?), but reading it `signal` for the config shouldn't happen.  This is an odd case where I am advocating runtime errors.

As noted in my other comment, I think the default value for `signal` should be provided to the `parseConfig` function in the `defaultConfig` parameter instead of being hard-coded into the `parseConf` function.

Other than these two things I don't think I have an issue with this PR.  Good work @jsoo1

2021-10-18 13:09 UTC, guygastineau commented on src/Xmobar/Config/Types.hs
> +  readsPrec _ s = [ (SignalChan Nothing, s) ]
Hmm, okay it does still seem wrong to me to have read instance for the signal channel do anything but fail, since it should never be used as such.

2021-10-18 13:09 UTC, guygastineau commented on src/Xmobar/Config/Parse.hs
> +        return (x (SignalChan Nothing),s)
This feels like an ad hoc solution that clutters the already dauntingly simple magic happening here.  I think the default value for `signal` should be provided by the `defaultConfig` argument.

2021-11-01 03:09 UTC, jsoo1 commented
@guygastineau @jaor I updated the error message when trying to parse the `signal` field and when `read`ing a `SignalChan`. What do you think?

2021-11-01 04:12 UTC, jaor commented
the error message looks good to me, and the code is reasonable.  could
we see an example of how this would be used in a realistic setting? and
also, i'm curious as to why the same thing cannot be done as
conveniently using dbus signals (sorry if you already explained that and
i've forgotten :))... as shown in PR #499 (which i should really
clean-up and merge one of these days), the latter is quite simple and
maybe could be reused somehow to the same effect (but i'm not opposed to
this alternative approach, if they're indeed alternatives!).

2021-11-08 01:57 UTC, jsoo1 commented
> could we see an example of how this would be used in a realistic setting? and also, i'm curious as to why the same thing cannot be done as conveniently using dbus signals (sorry if you already explained that and i've forgotten :))... as shown in PR #499 (which i should really clean-up and merge one of these days), the latter is quite simple and maybe could be reused somehow to the same effect (but i'm not opposed to this alternative approach, if they're indeed alternatives!).

I was using DBus signals before.  Since moving my xmobar configuration in to xmonad.hs, it seemed stringly typed and more cumbersome to use dbus than just sending messages across the TVar.

Here's what I have right now in xmonad.hs:

```hs
startXmobar :: IO (STM.TQueue String, STM.TMVar Xmobar.SignalType, ThreadId)
startXmobar = do
  xmobarQueue <- STM.newTQueueIO
  xmobarSignal <- STM.newEmptyTMVarIO
  conf <- xmobarConf xmobarSignal xmobarQueue
  xmobarProc <- forkIO (Xmobar.xmobar conf)
  pure (xmobarQueue, xmobarSignal, xmobarProc)


-- Later, using the TVar SignalType bound to a keybinding

toggleBar :: STM.TMVar Xmobar.SignalType -> X ()
toggleBar xmobarSignal = do
  broadcastMessage ToggleStruts
  io (STM.atomically (STM.putTMVar xmobarSignal (Xmobar.Toggle 0)))
  -- ^^^^ This is much nicer than constructing and sending a dbus message
  -- (not to mention, less error prone and faster)
  refresh
```

Here's my xmonad.hs where i've been trying  some new things out.

https://github.com/jsoo1/dotfiles/blob/release/xmonad/xmonad.hs#L71
https://github.com/jsoo1/dotfiles/blob/release/xmonad/xmonad.hs#L106

2021-11-21 22:08 UTC, merged

2021-11-21 22:30 UTC, jaor commented
merged.  thanks for your patience!

2021-11-22 01:17 UTC, jsoo1 commented
No problem! Thank you!

> On Sunday, Nov 21, 2021 at 2:30 PM, jao ***@***.*** ***@***.***)> wrote:
>
>
>
>
> merged. thanks for your patience!
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://urldefense.com/v3/__https://github.com/jaor/xmobar/pull/574*issuecomment-974909357__;Iw!!IKRxdwAv5BmarQ!L6OpG1d-EEGw7ICWAfmm4UYAEmOkRgapcKKj11H8KsCrxCI_gqKXRRlUx0wtAQ$), or unsubscribe (https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ACMTD2L27ACHKL3YXKOLI3LUNFXKFANCNFSM5EYKDLEQ__;!!IKRxdwAv5BmarQ!L6OpG1d-EEGw7ICWAfmm4UYAEmOkRgapcKKj11H8KsCrxCI_gqKXRRnc4cIimQ$).
>
>
>